import { useEffect, useRef, useState, type CSSProperties } from 'react'
import { useTranslation } from 'react-i18next'
import { useClickOutside } from '../../../hooks/useClickOutside'
import type { RecentReportFormat, RecentReportRow } from '../../../types/adminReports'
import { DownloadIcon } from './icons'
import './recentReportsPanel.css'

const DOWNLOAD_FORMATS: RecentReportFormat[] = ['csv', 'pdf', 'excel']
const FORMAT_EXTENSION: Record<RecentReportFormat, string> = { csv: 'csv', pdf: 'pdf', excel: 'xlsx' }
// Alto aproximado del menú de 3 formatos -- para decidir si abre hacia abajo o hacia arriba.
const MENU_HEIGHT_PX = 140
const MENU_GAP_PX = 6

// No existe todavía un backend que genere el archivo real (ver conversación) -- el placeholder
// contiene el mismo texto sin importar el formato elegido, solo cambia la extensión/nombre del
// archivo descargado. El día que exista un endpoint real, reemplazar solo este helper.
export function downloadMockReport(report: RecentReportRow, format: RecentReportFormat) {
  const content = `Report: ${report.name}\nDate Range: ${report.dateRangeLabel}\nGenerated By: ${report.generatedBy}\nCreated At: ${report.createdAt}\n`
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${report.name.replace(/\s+/g, '-')}.${FORMAT_EXTENSION[format]}`
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}

// Extraído de RecentReportsPanel.tsx -- reutilizado también por AllReportsModal.tsx (ver
// conversación: "el modal de All Reports también debe permitir descargar"), mismo componente en
// ambos lugares en vez de duplicar el dropdown de formato.
export function DownloadMenu({ report }: { report: RecentReportRow }) {
  const { t } = useTranslation()
  const [isOpen, setIsOpen] = useState(false)
  const [menuStyle, setMenuStyle] = useState<CSSProperties>({})
  const containerRef = useRef<HTMLDivElement>(null)
  const buttonRef = useRef<HTMLButtonElement>(null)
  useClickOutside(containerRef, () => setIsOpen(false))

  // Menú con position:fixed calculado desde el botón -- la tabla de Recent Reports/All Reports
  // tiene overflow-x:auto, que también recorta en vertical, así que un menú absolute quedaba cortado
  // (solo se veía "Excel"). Abre hacia abajo si entra en la ventana, si no hacia arriba.
  const openMenu = () => {
    const rect = buttonRef.current?.getBoundingClientRect()
    if (rect) {
      const openUp = window.innerHeight - rect.bottom < MENU_HEIGHT_PX + MENU_GAP_PX && rect.top > MENU_HEIGHT_PX
      setMenuStyle({
        position: 'fixed',
        right: window.innerWidth - rect.right,
        top: openUp ? 'auto' : rect.bottom + MENU_GAP_PX,
        bottom: openUp ? window.innerHeight - rect.top + MENU_GAP_PX : 'auto',
        zIndex: 60,
      })
    }
    setIsOpen(true)
  }

  // Un menú fixed no acompaña el scroll de la página/modal -- se cierra en vez de quedar flotando.
  useEffect(() => {
    if (!isOpen) return
    const close = () => setIsOpen(false)
    window.addEventListener('scroll', close, true)
    window.addEventListener('resize', close)
    return () => {
      window.removeEventListener('scroll', close, true)
      window.removeEventListener('resize', close)
    }
  }, [isOpen])

  return (
    <div className="admin-dropdown admin-recent-reports-action-dropdown" ref={containerRef}>
      {/* Sin tooltip "Download" (quedaba encima del menú al abrirlo); el aria-label sigue
          anunciando la acción a lectores de pantalla. */}
      <button
        ref={buttonRef}
        type="button"
        className="admin-recent-reports-icon-btn"
        aria-expanded={isOpen}
        aria-label={t('admin.reports.recent.download')}
        onClick={() => (isOpen ? setIsOpen(false) : openMenu())}
      >
        <DownloadIcon />
      </button>

      {isOpen && (
        <div className="admin-dropdown-menu admin-recent-reports-format-menu" role="listbox" style={menuStyle}>
          {DOWNLOAD_FORMATS.map((format) => (
            <button
              key={format}
              type="button"
              className="admin-dropdown-option"
              role="option"
              aria-selected={false}
              onClick={() => {
                downloadMockReport(report, format)
                setIsOpen(false)
              }}
            >
              {t(`admin.reports.exportFormats.${format}`)}
            </button>
          ))}
        </div>
      )}
    </div>
  )
}
