import { useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useClickOutside } from '../../../hooks/useClickOutside'
import { useDropdownFlip } from '../../../hooks/useDropdownFlip'
import { Tooltip } from '../Tooltip'
import type { RecentReportFormat, RecentReportRow } from '../../../types/adminReports'
import { DownloadIcon } from './icons'
import './recentReportsPanel.css'

const DOWNLOAD_FORMATS: RecentReportFormat[] = ['csv', 'pdf', 'excel']
const FORMAT_EXTENSION: Record<RecentReportFormat, string> = { csv: 'csv', pdf: 'pdf', excel: 'xlsx' }

// No existe todavía un backend que genere el archivo real (ver conversación) -- el placeholder
// contiene el mismo texto sin importar el formato elegido, solo cambia la extensión/nombre del
// archivo descargado. El día que exista un endpoint real, reemplazar solo este helper.
function downloadMockReport(report: RecentReportRow, format: RecentReportFormat) {
  const content = `Report: ${report.name}\nDate Range: ${report.dateRangeLabel}\nGenerated By: ${report.generatedBy}\nCreated At: ${report.createdAt}\n`
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${report.name.replace(/\s+/g, '-')}.${FORMAT_EXTENSION[format]}`
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}

// Extraído de RecentReportsPanel.tsx -- reutilizado también por AllReportsModal.tsx (ver
// conversación: "el modal de All Reports también debe permitir descargar"), mismo componente en
// ambos lugares en vez de duplicar el dropdown de formato.
export function DownloadMenu({ report }: { report: RecentReportRow }) {
  const { t } = useTranslation()
  const [isOpen, setIsOpen] = useState(false)
  const containerRef = useRef<HTMLDivElement>(null)
  useClickOutside(containerRef, () => setIsOpen(false))
  const openUpward = useDropdownFlip(containerRef, isOpen)

  return (
    <div className="admin-dropdown admin-recent-reports-action-dropdown" ref={containerRef}>
      <Tooltip content={t('admin.reports.recent.download')}>
        <button
          type="button"
          className="admin-recent-reports-icon-btn"
          aria-expanded={isOpen}
          aria-label={t('admin.reports.recent.download')}
          onClick={() => setIsOpen((value) => !value)}
        >
          <DownloadIcon />
        </button>
      </Tooltip>

      {isOpen && (
        <div className={`admin-dropdown-menu admin-recent-reports-format-menu${openUpward ? ' admin-dropdown-menu--up' : ''}`} role="listbox">
          {DOWNLOAD_FORMATS.map((format) => (
            <button
              key={format}
              type="button"
              className="admin-dropdown-option"
              role="option"
              aria-selected={false}
              onClick={() => {
                downloadMockReport(report, format)
                setIsOpen(false)
              }}
            >
              {t(`admin.reports.exportFormats.${format}`)}
            </button>
          ))}
        </div>
      )}
    </div>
  )
}
